### ISSUE TITLE
Need free option string to add --chmod under Windows

### ISSUE THREAD

**Issue by karland** [jerrysu/gulp-rsync#14]
I have run into the following issue under Windows: [https://github.com/mitchellh/vagrant/issues/3256](https://github.com/mitchellh/vagrant/issues/3256). When I call

```
rsync.exe -e ssh --chmod=ug=rwX,o=rxX -avtzP ...
```

my issue is fixed. However, I cannot find a way to pass the `--chmod`-option to gulp-rsync. Can you help or add a "free option string". That would be fantastic. Thank you.

**Comment by karland** [comment]
The same issue was already fixed with this [commit to rsyncwrapper](https://github.com/jedrichards/rsyncwrapper/commit/44db9e8511cb2a994762521bf6011588a56f1404). It would be fantastic if it could also be fixed here. Thanks.

**Comment by karland** [comment]
Sorry wrong button....

**Comment by yethee** [comment]
I had same issue. I implemented [temporary solution](https://github.com/yethee/gulp-rsync/commit/e24b0de021fd340f4bc1bcb1446e2c42296a61d2) in my fork of this repository.

**Comment by karland** [comment]
@yethee Thanks for the hint. This actually encouraged my to make a [PR #15](https://github.com/jerrysu/gulp-rsync/pull/15)

@jerrysu Good code. It was relatively easy to add new options and fix my problem in the source. Thanks.
