### ISSUE TITLE
does not work on windows and does not show any errors...

### ISSUE THREAD

**Issue by born2net** [jerrysu/gulp-rsync#19]
I am running the following command:

```

gulp.task('testRsync', function() {
    gulp.src('./_source/*.html')
        .pipe(rsync({
            options: {
                chmod: 'ugo=rwX',
                'r': true,
                'v': true,
                'delete': true,
                'verbose': true,
                'progress': true
            },
            username: 'root',
            root: '_source/',
            hostname: 'my_domain_here.com',
            destination: '/tmp',
            recursive: true
        }));
});
```

and all I get when I run it is:

[13:18:57] Using gulpfile C:\msweb\mswebsite_local\gulpfile.js
[13:18:57] Starting 'testRsync'...
[13:18:57] Finished 'testRsync' after 5.17 ms

now if I run my cygwin rsync, everything works fine...

any help is appreciated.

regards

**Comment by johannesjo** [comment]
Same problem, but on ubuntu.

**Comment by wesbos** [comment]
Same problem on OSX - any ideas?

**Comment by GenuineJD** [comment]
Bump OS X Yosemite.  Funny thing is, works find on one of my MacBooks, but not the other with the same versions of Node and NPM installed.

**Comment by tnguyen14** [comment]
Try `return gulp.src(...`

**Comment by monte-hayward** [comment]
Thanks, @tnguyen14 .  
Doc update PR: https://github.com/jerrysu/gulp-rsync/pull/24
```
// adding "return " to this fn worked.
gulp.task('deploy', function () {
  return gulp.src('_site/**')
    .pipe(rsync({
      username: 'foo',
      hostname: 'bar.host.com',
      destination: '/home/foo/foosite.com',
      incremental: true,
      recursive: true,
      compress: true,
      times: true,
      progress: true
    }));
});
```

**Comment by Gitward** [comment]
Seems that jerrysu is not working on this repo anymore,...

**Comment by ebaskoro** [comment]
PR approved and merged. Thank you @monte-hayward and everyone.
