### ISSUE TITLE
Clean doesn't seem to be working

### ISSUE THREAD

**Issue by Jakobud** [jerrysu/gulp-rsync#25]
I used the following:
```
gulp.src('build/**')
  .pipe(rsync({
    hostname: 'myremotehost.com',
    destination: '/tmp',
    times: true,
    recursive: true,
    clean: true
  }));
```

So to test, I run it and it successfully copies over everything in my build directory to the proper place on the remote server.

Next, in order to test that the `clean` option is working, I go into my `build` directory and delete one of the subdirectories. I then run my task again. I check on the remote server and the subdirectory that I deleted is still in the target directory. Shouldn't it have been deleted with clean?

Am I misunderstanding something about how `clean` works?

**Comment by Jakobud** [comment]
Well it's working now just fine for some reason. Not sure what I did different. Options are the same. Oh well.

**Comment by rctneil** [comment]
@Jakobud Hey, i'm having exactly the same issue as this. Any chance you know what you did to resolve it?

**Comment by Jakobud** [comment]
I have no idea. It just worked all the sudden...
