### ISSUE TITLE
Is this managed?

### ISSUE THREAD

**Issue by stevelacy** [jerrysu/gulp-rsync#31]
@jerrysu are you still managing this project, or is this just off to the wayside?

**Comment by gilbarbara** [comment]
:+1:

**Comment by frob** [comment]
Do you mean, Is this project still being maintained? I would like to know as well.

**Comment by v3nt** [comment]
+1

**Comment by Preen** [comment]
+1

**Comment by ebaskoro** [comment]
Hi all. The answer is *YES*.
We are in the process of reviewing any outstanding pull requests and sorting out the open issues. Meanwhile please bear with us and thank you once again for your support.
Cheers.
